# Generated by Django 5.0.2 on 2025-05-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('expired', 'Expired')], default='scheduled', max_length=10),
        ),
    ]
